<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="KARMA" ignored="0" name="expectedException tests" tests="5" failures="2" timestamp="2020-12-27T17:34:55 CST" time="0.354" errors="0">
  <testcase name="exceptionMessageOneTest" time="0.087" classname="org.expectedexception.ExpectedExceptionMessageDemo"/>
  <testcase name="exceptionMessageThreeTest" time="0.002" classname="org.expectedexception.ExpectedExceptionMessageDemo">
    <failure type="org.testng.TestException" message="
The exception was thrown with the wrong message: expected &amp;quot;Pass Message test&amp;quot; but got &amp;quot;Fail Message test&amp;quot;">
      <![CDATA[org.testng.TestException: 
The exception was thrown with the wrong message: expected "Pass Message test" but got "Fail Message test"
at java.util.ArrayList.forEach(Unknown Source)
Caused by: java.io.IOException: Fail Message test
at org.expectedexception.ExpectedExceptionMessageDemo.exceptionMessageThreeTest(ExpectedExceptionMessageDemo.java:25)
... 22 more
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- exceptionMessageThreeTest -->
  <testcase name="exceptionMessageTwoTest" time="0.004" classname="org.expectedexception.ExpectedExceptionMessageDemo"/>
  <testcase name="exceptionOneTest" time="0.003" classname="org.expectedexception.ExpectedExceptionDemo"/>
  <testcase name="exceptionTwoTest" time="0.004" classname="org.expectedexception.ExpectedExceptionDemo">
    <failure type="org.testng.TestException" message="
Expected exception of any of types [class java.io.IOException, class java.lang.NullPointerException] but got java.lang.Exception">
      <![CDATA[org.testng.TestException: 
Expected exception of any of types [class java.io.IOException, class java.lang.NullPointerException] but got java.lang.Exception
at java.util.ArrayList.forEach(Unknown Source)
Caused by: java.lang.Exception
at org.expectedexception.ExpectedExceptionDemo.exceptionTwoTest(ExpectedExceptionDemo.java:18)
... 22 more
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- exceptionTwoTest -->
</testsuite> <!-- expectedException tests -->
