{"name":"exceptionTwoTest","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"\nExpected exception of any of types [class java.io.IOException, class java.lang.NullPointerException] but got java.lang.Exception","trace":"org.testng.TestException: \nExpected exception of any of types [class java.io.IOException, class java.lang.NullPointerException] but got java.lang.Exception\r\n\tat org.testng.internal.ExpectedExceptionsHolder.wrongException(ExpectedExceptionsHolder.java:68)\r\n\tat org.testng.internal.TestInvoker.considerExceptions(TestInvoker.java:737)\r\n\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:635)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)\r\n\tat org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)\r\n\tat org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.util.ArrayList.forEach(Unknown Source)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:764)\r\n\tat org.testng.TestRunner.run(TestRunner.java:585)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:384)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:286)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1140)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1069)\r\n\tat org.testng.TestNG.run(TestNG.java:1037)\r\n\tat org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)\r\n\tat org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)\r\n\tat org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)\r\nCaused by: java.lang.Exception\r\n\tat org.expectedexception.ExpectedExceptionDemo.exceptionTwoTest(ExpectedExceptionDemo.java:18)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)\r\n\tat java.lang.reflect.Method.invoke(Unknown Source)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)\r\n\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)\r\n\t... 22 more\r\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1609111282871,"stop":1609111282875,"uuid":"6cfb5593-770c-4af8-9c54-4c8ebc232091","historyId":"bce3b8585e23335b2993898d759e8304","fullName":"org.expectedexception.ExpectedExceptionDemo.exceptionTwoTest","labels":[{"name":"package","value":"org.expectedexception.ExpectedExceptionDemo"},{"name":"testClass","value":"org.expectedexception.ExpectedExceptionDemo"},{"name":"testMethod","value":"exceptionTwoTest"},{"name":"parentSuite","value":"Default suite"},{"name":"suite","value":"Default test"},{"name":"subSuite","value":"org.expectedexception.ExpectedExceptionDemo"},{"name":"host","value":"KARMA"},{"name":"thread","value":"21000@KARMA.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[]}